### ISSUE TITLE
Could not obtain dataset from ckan

### ISSUE THREAD

**Issue by Jan-Marcek** [OpenDataNode/UVPlugin-filesToCKAN#7] opened 2015-06-02 09:11 UTC
When user runs pipeline uv-l-filesToCkan for the first time then uv-l-filesToCkan fails. However, when user runs pipeline for the second time then it works fine.

version: UV_Plugins_v2.0.1

uv.log:

```
Execution failed because: Could not obtain dataset from CKAN.eu.unifiedviews.dpu.DPUException: Could not obtain dataset from CKAN. at eu.unifiedviews.helpers.dpu.context.ContextUtils.dpuException(ContextUtils.java:181) at eu.unifiedviews.plugins.loader.filestockan.FilesToCkan.innerExecute(FilesToCkan.java:197) at eu.unifiedviews.helpers.dpu.exec.AbstractDpu.execute(AbstractDpu.java:117) at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.executeInstance(DPUExecutor.java:232) at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.execute(DPUExecutor.java:370) at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.run(DPUExecutor.java:452) at java.lang.Thread.run(Thread.java:745)
```

ckan - internalcatalog

```
[Fri May 29 13:55:23 2015] [error] 2015-05-29 13:55:23,084 ERROR [ckanext] Error sending request to http://127.0.0.1:28080/master/api/1/pipelines: {"error":"Could not commit JPA transaction; nested exception is javax.persistence.RollbackException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.5.1.v20130918-f2b9fc5): org.eclipse.persistence.exceptions.DatabaseException\\nInternal Exception: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint \\"ppl_model_name_key\\"\\n  Detail: Key (name)=(dataset) already exists.\\nError Code: 0\\nCall: INSERT INTO ppl_model (ID, DESCRIPTION, last_change, NAME, visibility, organization_id, user_id) VALUES (?, ?, ?, ?, ?, ?, ?)\\n\\tbind => [2, , 2015-05-29 13:55:22.794, dataset, 0, null, 1]\\nQuery: InsertObjectQuery(cz.cuni.mff.xrg.odcs.commons.app.pipeline.Pipeline@2a9)"}
[Fri May 29 13:55:23 2015] [error] Traceback (most recent call last):
[Fri May 29 13:55:23 2015] [error]   File "/usr/share/python/odn-ckan-shared/lib/python2.7/site-packages/ckanext/controllers/pipeline.py", line 351, in create_pipe_manually
[Fri May 29 13:55:23 2015] [error]     new_pipe = uv_api.create_pipeline(name, description, user_id, org_id)
[Fri May 29 13:55:23 2015] [error]   File "/usr/share/python/odn-ckan-shared/lib/python2.7/site-packages/ckanext/pipeline/uv_helper.py", line 98, in create_pipeline
[Fri May 29 13:55:23 2015] [error]     return self._send_request_with_data(uv_url, json.dumps(data))
[Fri May 29 13:55:23 2015] [error]   File "/usr/share/python/odn-ckan-shared/lib/python2.7/site-packages/ckanext/pipeline/uv_helper.py", line 72, in _send_request_with_data
[Fri May 29 13:55:23 2015] [error]     raise Exception("Error sending request to {0}: {1}".format(uv_url, response.text))
[Fri May 29 13:55:23 2015] [error] Exception: Error sending request to http://127.0.0.1:28080/master/api/1/pipelines: {"error":"Could not commit JPA transaction; nested exception is javax.persistence.RollbackException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.5.1.v20130918-f2b9fc5): org.eclipse.persistence.exceptions.DatabaseException\\nInternal Exception: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint \\"ppl_model_name_key\\"\\n  Detail: Key (name)=(dataset) already exists.\\nError Code: 0\\nCall: INSERT INTO ppl_model (ID, DESCRIPTION, last_change, NAME, visibility, organization_id, user_id) VALUES (?, ?, ?, ?, ?, ?, ?)\\n\\tbind => [2, , 2015-05-29 13:55:22.794, dataset, 0, null, 1]\\nQuery: InsertObjectQuery(cz.cuni.mff.xrg.odcs.commons.app.pipeline.Pipeline@2a9)"}
```

**Comment by skrchnavy** [comment] 2015-06-02 11:17
if included in 1.0.3 then hotfix branch to be created to fix this bug.

**Comment by ghost** [comment] 2015-06-02 12:11
when filesToCkan dpu tries to retrieve dataset which is associated with 
pipeline, the CKAN calls UV/master back for list of pipelines?
 From log:

|Fri May 29 13:55:23 2015] [error] Exception: Error sending request to http://127.0.0.1:28080/master/api/1/pipelines: {"error":"Could not commit JPA transaction; nested exception is javax.persistence.RollbackException: Exception [EclipseLink-4002](Eclipse Persistence Services - 2.5.1.v20130918-f2b9fc5): org.eclipse.persistence.exceptions.DatabaseException\nInternal Exception: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint \"ppl_model_name_key\"\n  Detail: Key (name)=(dataset) already exists.\nError Code: 0\nCall: INSERT INTO ppl_model (ID, DESCRIPTION, last_change, NAME, visibility, organization_id, user_id) VALUES (?, ?, ?, ?, ?, ?, ?)\n\tbind => [2, , 2015-05-29 13:55:22.794, dataset, 0, null, 1]\nQuery: InsertObjectQuery(cz.cuni.mff.xrg.odcs.commons.app.pipeline.Pipeline@2a9)"}

it even seems this is POST request? causing some unique constraint violation in UV?
What happens in CKAN, I request to assign this issue to CKAN-proxy developer. (Why the hell is CKAN POSTing back to UV).
It the request is GET, then what the hell is implemented in master-api ? Does GETing the API modify database?

In any case, this is not issue of filesToCkan DPU.
|

**Comment by jindrichmynarz** [comment] 2015-06-04 15:27
The same issue can be encountered for l-rdfToCkan. @mkl-eea-sk, if this is not an issue of l-filesToCkan, then what is causing it and how can we fix it?

**Comment by mvi-eea-sk** [comment] 2015-06-05 13:23
Thats two different bugs !!!
1. The bug in CKAN log is caused by creating Pipeline from CKAN GUI:
   Pipelines tab > Add pipeline > Create manually > filled Name and Description > ckan sends req to  UV api to create it > response from UV is (from the log above): I have already pipeline with this name and the name must be unique
   btw: I want that master (UV) api sends human readable errors in the JSON response !!! so i can present it in GUI !!! what help is when it returns stacktrace to CKAN ???
2. the second problem ... I don't know the cause
   UV probably called the package_show CKAN API call (through internal_api), but ... the cause isn't logged. My question is, why it isn't logged in the dpu? CKAN api calls return properly described cause of the error (except when its internal error) ...

**Comment by ghost** [comment] 2015-06-05 13:27
Great, at least we know that ckan is not calling back UV when resource 
is updated, it is just bad part of logs here...
will take a look on this when available.

**Comment by jindrichmynarz** [comment] 2015-06-05 13:57
@mvi-eea-sk: I'm not sure this issue is related to creating pipeline from CKAN. At least this doesn't seem to be a part of the issue I'm experiencing. In my case, I have associated the dataset with an existing pipeline.

According to Apache logs (i.e. /var/log/apache2/odn-ckan-ic.access.log), there's an unauthorized POST request to `/internalcatalog/api/action/internal_api`:

```
127.0.0.1 - - [05/Jun/2015:15:51:26 +0200] "POST /internalcatalog/api/action/internal_api HTTP/1.1" 403 487 "-" "Apache-HttpClient/4.3.3 (java 1.5)"
```

The internal CKAN error log might reveal more about the error. Here's the last 100 lines:

```
[Fri Jun 05 15:50:53 2015] [error] 2015-06-05 15:50:53,052 INFO  [ckan.lib.base]  /dataset/slovak-national-library-bibliographic-data/pipelines render time 0.244 seconds
[Fri Jun 05 15:50:53 2015] [error] 2015-06-05 15:50:53,268 INFO  [ckanext.odn.cas] identify
[Fri Jun 05 15:50:53 2015] [error] 2015-06-05 15:50:53,268 INFO  [ckanext.odn.cas] user casadmin
[Fri Jun 05 15:50:53 2015] [error] 2015-06-05 15:50:53,268 INFO  [ckanext.odn.cas] identity: ['authenticator', 'repoze.who.userid', 'userdata', 'timestamp', 'repoze.who.plugins.auth_tkt.userid', 'tokens', 'identifier']
[Fri Jun 05 15:50:53 2015] [error] 2015-06-05 15:50:53,268 INFO  [ckanext.odn.cas] attributes: {}
[Fri Jun 05 15:50:53 2015] [error] 2015-06-05 15:50:53,268 INFO  [ckanext.odn.cas] user id : casadmin
[Fri Jun 05 15:50:53 2015] [error] 2015-06-05 15:50:53,268 INFO  [ckanext.odn.cas] user data : 
[Fri Jun 05 15:50:53 2015] [error] 2015-06-05 15:50:53,275 INFO  [ckanext.odn.cas] identify
[Fri Jun 05 15:50:53 2015] [error] 2015-06-05 15:50:53,275 INFO  [ckanext.odn.cas] user casadmin
[Fri Jun 05 15:50:53 2015] [error] 2015-06-05 15:50:53,275 INFO  [ckanext.odn.cas] identity: ['authenticator', 'repoze.who.userid', 'userdata', 'timestamp', 'repoze.who.plugins.auth_tkt.userid', 'tokens', 'identifier']
[Fri Jun 05 15:50:53 2015] [error] 2015-06-05 15:50:53,276 INFO  [ckanext.odn.cas] attributes: {}
[Fri Jun 05 15:50:53 2015] [error] 2015-06-05 15:50:53,276 INFO  [ckanext.odn.cas] user id : casadmin
[Fri Jun 05 15:50:53 2015] [error] 2015-06-05 15:50:53,276 INFO  [ckanext.odn.cas] user data : 
[Fri Jun 05 15:50:53 2015] [error] 2015-06-05 15:50:53,278 INFO  [ckan.lib.base]  /api/i18n/en render time 0.004 seconds
[Fri Jun 05 15:50:54 2015] [error] 2015-06-05 15:50:54,879 INFO  [ckanext.odn.cas] identify
[Fri Jun 05 15:50:54 2015] [error] 2015-06-05 15:50:54,879 INFO  [ckanext.odn.cas] user casadmin
[Fri Jun 05 15:50:54 2015] [error] 2015-06-05 15:50:54,879 INFO  [ckanext.odn.cas] identity: ['authenticator', 'repoze.who.userid', 'userdata', 'timestamp', 'repoze.who.plugins.auth_tkt.userid', 'tokens', 'identifier']
[Fri Jun 05 15:50:54 2015] [error] 2015-06-05 15:50:54,879 INFO  [ckanext.odn.cas] attributes: {}
[Fri Jun 05 15:50:54 2015] [error] 2015-06-05 15:50:54,879 INFO  [ckanext.odn.cas] user id : casadmin
[Fri Jun 05 15:50:54 2015] [error] 2015-06-05 15:50:54,879 INFO  [ckanext.odn.cas] user data : 
[Fri Jun 05 15:50:55 2015] [error] 2015-06-05 15:50:55,022 INFO  [ckan.lib.base]  /dataset/slovak-national-library-bibliographic-data/pipelines/choose_action render time 0.146 seconds
[Fri Jun 05 15:50:55 2015] [error] 2015-06-05 15:50:55,165 INFO  [ckanext.odn.cas] identify
[Fri Jun 05 15:50:55 2015] [error] 2015-06-05 15:50:55,165 INFO  [ckanext.odn.cas] user casadmin
[Fri Jun 05 15:50:55 2015] [error] 2015-06-05 15:50:55,165 INFO  [ckanext.odn.cas] identity: ['authenticator', 'repoze.who.userid', 'userdata', 'timestamp', 'repoze.who.plugins.auth_tkt.userid', 'tokens', 'identifier']
[Fri Jun 05 15:50:55 2015] [error] 2015-06-05 15:50:55,165 INFO  [ckanext.odn.cas] attributes: {}
[Fri Jun 05 15:50:55 2015] [error] 2015-06-05 15:50:55,165 INFO  [ckanext.odn.cas] user id : casadmin
[Fri Jun 05 15:50:55 2015] [error] 2015-06-05 15:50:55,165 INFO  [ckanext.odn.cas] user data : 
[Fri Jun 05 15:50:55 2015] [error] 2015-06-05 15:50:55,172 INFO  [ckanext.odn.cas] identify
[Fri Jun 05 15:50:55 2015] [error] 2015-06-05 15:50:55,172 INFO  [ckanext.odn.cas] user casadmin
[Fri Jun 05 15:50:55 2015] [error] 2015-06-05 15:50:55,172 INFO  [ckanext.odn.cas] identity: ['authenticator', 'repoze.who.userid', 'userdata', 'timestamp', 'repoze.who.plugins.auth_tkt.userid', 'tokens', 'identifier']
[Fri Jun 05 15:50:55 2015] [error] 2015-06-05 15:50:55,172 INFO  [ckanext.odn.cas] attributes: {}
[Fri Jun 05 15:50:55 2015] [error] 2015-06-05 15:50:55,172 INFO  [ckanext.odn.cas] user id : casadmin
[Fri Jun 05 15:50:55 2015] [error] 2015-06-05 15:50:55,172 INFO  [ckanext.odn.cas] user data : 
[Fri Jun 05 15:50:55 2015] [error] 2015-06-05 15:50:55,175 INFO  [ckan.lib.base]  /api/i18n/en render time 0.005 seconds
[Fri Jun 05 15:50:57 2015] [error] 2015-06-05 15:50:57,352 INFO  [ckanext.odn.cas] identify
[Fri Jun 05 15:50:57 2015] [error] 2015-06-05 15:50:57,352 INFO  [ckanext.odn.cas] user casadmin
[Fri Jun 05 15:50:57 2015] [error] 2015-06-05 15:50:57,352 INFO  [ckanext.odn.cas] identity: ['authenticator', 'repoze.who.userid', 'userdata', 'timestamp', 'repoze.who.plugins.auth_tkt.userid', 'tokens', 'identifier']
[Fri Jun 05 15:50:57 2015] [error] 2015-06-05 15:50:57,352 INFO  [ckanext.odn.cas] attributes: {}
[Fri Jun 05 15:50:57 2015] [error] 2015-06-05 15:50:57,353 INFO  [ckanext.odn.cas] user id : casadmin
[Fri Jun 05 15:50:57 2015] [error] 2015-06-05 15:50:57,353 INFO  [ckanext.odn.cas] user data : 
[Fri Jun 05 15:50:57 2015] [error] 2015-06-05 15:50:57,406 DEBUG [ckanext] uv_helper sending request to: http://127.0.0.1:28080/master/api/1/pipelines?organizationExternalId=comsode
[Fri Jun 05 15:50:57 2015] [error] 2015-06-05 15:50:57,681 INFO  [ckan.lib.base]  /dataset/slovak-national-library-bibliographic-data/pipelines/choose_pipeline render time 0.331 seconds
[Fri Jun 05 15:50:57 2015] [error] 2015-06-05 15:50:57,898 INFO  [ckanext.odn.cas] identify
[Fri Jun 05 15:50:57 2015] [error] 2015-06-05 15:50:57,899 INFO  [ckanext.odn.cas] user casadmin
[Fri Jun 05 15:50:57 2015] [error] 2015-06-05 15:50:57,899 INFO  [ckanext.odn.cas] identity: ['authenticator', 'repoze.who.userid', 'userdata', 'timestamp', 'repoze.who.plugins.auth_tkt.userid', 'tokens', 'identifier']
[Fri Jun 05 15:50:57 2015] [error] 2015-06-05 15:50:57,899 INFO  [ckanext.odn.cas] attributes: {}
[Fri Jun 05 15:50:57 2015] [error] 2015-06-05 15:50:57,899 INFO  [ckanext.odn.cas] user id : casadmin
[Fri Jun 05 15:50:57 2015] [error] 2015-06-05 15:50:57,899 INFO  [ckanext.odn.cas] user data : 
[Fri Jun 05 15:50:57 2015] [error] 2015-06-05 15:50:57,905 INFO  [ckanext.odn.cas] identify
[Fri Jun 05 15:50:57 2015] [error] 2015-06-05 15:50:57,905 INFO  [ckanext.odn.cas] user casadmin
[Fri Jun 05 15:50:57 2015] [error] 2015-06-05 15:50:57,905 INFO  [ckanext.odn.cas] identity: ['authenticator', 'repoze.who.userid', 'userdata', 'timestamp', 'repoze.who.plugins.auth_tkt.userid', 'tokens', 'identifier']
[Fri Jun 05 15:50:57 2015] [error] 2015-06-05 15:50:57,905 INFO  [ckanext.odn.cas] attributes: {}
[Fri Jun 05 15:50:57 2015] [error] 2015-06-05 15:50:57,905 INFO  [ckanext.odn.cas] user id : casadmin
[Fri Jun 05 15:50:57 2015] [error] 2015-06-05 15:50:57,905 INFO  [ckanext.odn.cas] user data : 
[Fri Jun 05 15:50:57 2015] [error] 2015-06-05 15:50:57,907 INFO  [ckan.lib.base]  /api/i18n/en render time 0.004 seconds
[Fri Jun 05 15:51:01 2015] [error] 2015-06-05 15:51:01,181 INFO  [ckanext.odn.cas] identify
[Fri Jun 05 15:51:01 2015] [error] 2015-06-05 15:51:01,182 INFO  [ckanext.odn.cas] user casadmin
[Fri Jun 05 15:51:01 2015] [error] 2015-06-05 15:51:01,182 INFO  [ckanext.odn.cas] identity: ['authenticator', 'repoze.who.userid', 'userdata', 'timestamp', 'repoze.who.plugins.auth_tkt.userid', 'tokens', 'identifier']
[Fri Jun 05 15:51:01 2015] [error] 2015-06-05 15:51:01,182 INFO  [ckanext.odn.cas] attributes: {}
[Fri Jun 05 15:51:01 2015] [error] 2015-06-05 15:51:01,182 INFO  [ckanext.odn.cas] user id : casadmin
[Fri Jun 05 15:51:01 2015] [error] 2015-06-05 15:51:01,182 INFO  [ckanext.odn.cas] user data : 
[Fri Jun 05 15:51:01 2015] [error] 2015-06-05 15:51:01,184 DEBUG [ckanext] uv_helper sending request to: http://127.0.0.1:28080/master/api/1/pipelines/3
[Fri Jun 05 15:51:01 2015] [error] 2015-06-05 15:51:01,349 INFO  [ckan.lib.base]  /dataset/slovak-national-library-bibliographic-data/pipelines render time 0.171 seconds
[Fri Jun 05 15:51:01 2015] [error] 2015-06-05 15:51:01,418 INFO  [ckanext.odn.cas] identify
[Fri Jun 05 15:51:01 2015] [error] 2015-06-05 15:51:01,418 INFO  [ckanext.odn.cas] user casadmin
[Fri Jun 05 15:51:01 2015] [error] 2015-06-05 15:51:01,418 INFO  [ckanext.odn.cas] identity: ['authenticator', 'repoze.who.userid', 'userdata', 'timestamp', 'repoze.who.plugins.auth_tkt.userid', 'tokens', 'identifier']
[Fri Jun 05 15:51:01 2015] [error] 2015-06-05 15:51:01,418 INFO  [ckanext.odn.cas] attributes: {}
[Fri Jun 05 15:51:01 2015] [error] 2015-06-05 15:51:01,418 INFO  [ckanext.odn.cas] user id : casadmin
[Fri Jun 05 15:51:01 2015] [error] 2015-06-05 15:51:01,418 INFO  [ckanext.odn.cas] user data : 
[Fri Jun 05 15:51:01 2015] [error] 2015-06-05 15:51:01,656 WARNI [ckan.lib.maintain] Function get_action() in module ckan.lib.helpers has been deprecated and will be removed in a later release of ckan. helpers.get_action() is deprecated and will be removed in a future version of CKAN. Instead, please use the extra_vars param to render() in your controller to pass results from action functions to your templates.
[Fri Jun 05 15:51:01 2015] [error] 2015-06-05 15:51:01,698 DEBUG [ckanext] uv_helper sending request to: http://127.0.0.1:28080/master/api/1/pipelines/3
[Fri Jun 05 15:51:01 2015] [error] 2015-06-05 15:51:01,840 DEBUG [ckanext] uv_helper sending request to: http://127.0.0.1:28080/master/api/1/pipelines/3/executions/last
[Fri Jun 05 15:51:01 2015] [error] 2015-06-05 15:51:01,987 DEBUG [ckanext] uv_helper sending request to: http://127.0.0.1:28080/master/api/1/pipelines/3/executions/pending
[Fri Jun 05 15:51:02 2015] [error] 2015-06-05 15:51:02,119 DEBUG [ckanext] uv_helper sending request to: http://127.0.0.1:28080/master/api/1/pipelines/3/schedules/~all/scheduledexecutions
[Fri Jun 05 15:51:02 2015] [error] 2015-06-05 15:51:02,251 WARNI [ckan.lib.maintain] Function get_action() in module ckan.lib.helpers has been deprecated and will be removed in a later release of ckan. helpers.get_action() is deprecated and will be removed in a future version of CKAN. Instead, please use the extra_vars param to render() in your controller to pass results from action functions to your templates.
[Fri Jun 05 15:51:02 2015] [error] 2015-06-05 15:51:02,324 INFO  [ckan.lib.base]  /dataset/slovak-national-library-bibliographic-data/pipelines render time 0.914 seconds
[Fri Jun 05 15:51:02 2015] [error] 2015-06-05 15:51:02,503 INFO  [ckanext.odn.cas] identify
[Fri Jun 05 15:51:02 2015] [error] 2015-06-05 15:51:02,503 INFO  [ckanext.odn.cas] user casadmin
[Fri Jun 05 15:51:02 2015] [error] 2015-06-05 15:51:02,503 INFO  [ckanext.odn.cas] identity: ['authenticator', 'repoze.who.userid', 'userdata', 'timestamp', 'repoze.who.plugins.auth_tkt.userid', 'tokens', 'identifier']
[Fri Jun 05 15:51:02 2015] [error] 2015-06-05 15:51:02,503 INFO  [ckanext.odn.cas] attributes: {}
[Fri Jun 05 15:51:02 2015] [error] 2015-06-05 15:51:02,503 INFO  [ckanext.odn.cas] user id : casadmin
[Fri Jun 05 15:51:02 2015] [error] 2015-06-05 15:51:02,503 INFO  [ckanext.odn.cas] user data : 
[Fri Jun 05 15:51:02 2015] [error] 2015-06-05 15:51:02,511 INFO  [ckanext.odn.cas] identify
[Fri Jun 05 15:51:02 2015] [error] 2015-06-05 15:51:02,511 INFO  [ckanext.odn.cas] user casadmin
[Fri Jun 05 15:51:02 2015] [error] 2015-06-05 15:51:02,511 INFO  [ckanext.odn.cas] identity: ['authenticator', 'repoze.who.userid', 'userdata', 'timestamp', 'repoze.who.plugins.auth_tkt.userid', 'tokens', 'identifier']
[Fri Jun 05 15:51:02 2015] [error] 2015-06-05 15:51:02,511 INFO  [ckanext.odn.cas] attributes: {}
[Fri Jun 05 15:51:02 2015] [error] 2015-06-05 15:51:02,511 INFO  [ckanext.odn.cas] user id : casadmin
[Fri Jun 05 15:51:02 2015] [error] 2015-06-05 15:51:02,511 INFO  [ckanext.odn.cas] user data : 
[Fri Jun 05 15:51:02 2015] [error] 2015-06-05 15:51:02,514 INFO  [ckan.lib.base]  /api/i18n/en render time 0.004 seconds
[Fri Jun 05 15:51:27 2015] [error] 2015-06-05 15:51:27,959 INFO  [ckanext.odn.cas] cas url: None
[Fri Jun 05 15:51:27 2015] [error] 2015-06-05 15:51:27,959 INFO  [ckanext.odn.cas] Using roles properties file: /etc/odn-simple/odn-ckan-ic/roles.properties
[Fri Jun 05 15:51:27 2015] [error] 2015-06-05 15:51:27,960 INFO  [ckanext.odn.cas] is_updating_allowed: True
[Fri Jun 05 15:51:28 2015] [error] 2015-06-05 15:51:28,103 INFO  [ckanext.odn.cas] identify
[Fri Jun 05 15:51:28 2015] [error] 2015-06-05 15:51:28,103 INFO  [ckanext.odn.cas] user 
[Fri Jun 05 15:51:28 2015] [error] 2015-06-05 15:51:28,110 INFO  [ckanext.odn.cas] identify
[Fri Jun 05 15:51:28 2015] [error] 2015-06-05 15:51:28,110 INFO  [ckanext.odn.cas] user 
[Fri Jun 05 15:51:28 2015] [error] 2015-06-05 15:51:28,136 DEBUG [ckanext] internal_api: Setting user to casadmin
[Fri Jun 05 15:51:28 2015] [error] 2015-06-05 15:51:28,136 DEBUG [ckanext] internal_api: action = package_show
[Fri Jun 05 15:51:28 2015] [error] 2015-06-05 15:51:28,136 DEBUG [ckanext] internal_api: user_id = casadmin
[Fri Jun 05 15:51:28 2015] [error] 2015-06-05 15:51:28,137 INFO  [ckan.lib.base]  /api/action/internal_api render time 0.028 seconds
```

May it be that the `org.opendatanode.CKAN.secret.token` in UnifiedViews configuration is generated invalid? How can I test if the secret token is valid?

**Comment by jindrichmynarz** [comment] 2015-06-06 15:14
I tried replacing the DPU with a previous version that worked. Doing that didn't have any effect, so I assume the bug is not in the DPU but instead was introduced to the CKAN API. What repository is providing the API?

**Comment by Jan-Marcek** [comment] 2015-06-08 06:48
token has to be same : `org.opendatanode.CKAN.secret.token` @/etc/unifiedviews/backend-config.properties and `ckan.auth.internal_api.token`@/etc/odn-simple/odn-ckan-ic/production.ini

from https://github.com/OpenDataNode/UVPlugin-filesToCKAN/tree/v1.0.2

**Comment by Jan-Marcek** [comment] 2015-06-08 06:51
@jindrichmynarz 's instance was quite different, because it was installed by upgrade. We have to look closely on this scenario. @mkl-eea-sk and @mvi-eea-sk Could we have better messages if the token is not same?

**Comment by mvi-eea-sk** [comment] 2015-06-11 08:13
if the JSON returned with the Http Error 403 contains error message like "internal api: Authentication failed" it means the token is wrong

**Comment by Jan-Marcek** [comment] 2015-06-11 08:44
set new token only when installation runs for the first time https://github.com/OpenDataNode/odn-box/commit/f9e8bf9efeed991e94b89171d34dd68804efb879

**Comment by Jan-Marcek** [comment] 2015-06-12 07:57
another similar issue https://github.com/OpenDataNode/open-data-node/issues/153

**Comment by ghost** [comment] 2015-06-23 09:10
I am unable to reproduce using this description, closing for now.

**Closed as completed by ghost** 2015-06-23 09:10 UTC
Labels: invalid
